# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sb_adj',
            field=models.CharField(choices=[('奇怪', '奇怪'), ('白目', '白目'), ('有病', '有病'), ('自戀', '自戀'), ('搞笑', '搞笑'), ('孤僻', '孤僻'), ('嚴肅', '嚴肅'), ('無趣', '無趣'), ('奇耙', '奇耙'), ('可怕', '可怕'), ('笨蛋', '笨蛋'), ('健忘', '健忘'), ('厲害', '厲害'), ('正常', '正常'), ('懶惰', '懶惰')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='sth_adj',
            field=models.CharField(choices=[('扯', '扯'), ('蠢', '蠢'), ('煩', '煩'), ('誇張', '誇張'), ('有趣', '有趣'), ('好笑', '好笑'), ('丟臉', '丟臉'), ('瘋狂', '瘋狂'), ('誇張', '誇張'), ('無聊', '無聊'), ('幼稚', '幼稚'), ('難忘', '難忘'), ('開心', '開心')], max_length=100, null=True),
        ),
    ]
