# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='sb_story',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='sb_thing',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
