# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='text',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.AddField(
            model_name='story',
            name='itjcts',
            field=models.CharField(choices=[('哎', '哎'), ('哈哈', '哈哈'), ('呵呵', '呵呵'), ('顆顆', '顆顆')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='mark',
            field=models.CharField(choices=[('~', '~'), ('!', '!'), ('XD', 'XD'), ('>///<', '>///<'), ('^^', '^^'), (':)', ':)'), ('。', '。')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_about',
            field=models.CharField(choices=[('很喜歡', '很喜歡'), ('不喜歡', '不喜歡'), ('不吃', '不吃'), ('討厭', '討厭'), ('怕', '怕'), ('常常', '常常')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_adj',
            field=models.CharField(choices=[('奇怪', '奇怪'), ('白目', '白目'), ('有病', '有病'), ('自戀', '自戀'), ('搞笑', '搞笑')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_adv',
            field=models.CharField(choices=[('有點', '有點'), ('非常', '非常'), ('蠻', '蠻'), ('超級', '超級'), ('史上無敵', '史上無敵')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_gender',
            field=models.CharField(choices=[('他', '他'), ('她', '她')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_story',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sb_thing',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='sth_adj',
            field=models.CharField(choices=[('扯', '扯'), ('蠢', '蠢'), ('有趣', '有趣'), ('好笑', '好笑'), ('丟臉', '丟臉'), ('瘋狂', '瘋狂'), ('誇張', '誇張'), ('無聊', '無聊'), ('幼稚', '幼稚'), ('難忘', '難忘'), ('開心', '開心')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='who',
            field=models.CharField(choices=[('我們', '我們'), ('他', '他'), ('她', '她')], max_length=100, null=True),
        ),
    ]
