# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_storyauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storys', to='story.StoryAuthor'),
        ),
    ]
