# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0002_auto_20171126_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='story_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='itjcts',
            field=models.CharField(choices=[('哎', '哎'), ('哈哈', '哈哈'), ('呵呵', '呵呵'), ('顆顆', '顆顆'), ('嘿丟', '嘿丟')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='sb_about',
            field=models.CharField(choices=[('很喜歡', '很喜歡'), ('不喜歡', '不喜歡'), ('不吃', '不吃'), ('討厭', '討厭'), ('怕', '怕'), ('常常', '常常'), ('很會', '很會'), ('曾經', '曾經')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='sb_adj',
            field=models.CharField(choices=[('humor', 'humor'), ('奇怪', '奇怪'), ('白目', '白目'), ('有病', '有病'), ('自戀', '自戀'), ('搞笑', '搞笑'), ('孤僻', '孤僻'), ('嚴肅', '嚴肅'), ('無趣', '無趣'), ('奇耙', '奇耙'), ('可怕', '可怕'), ('笨蛋', '笨蛋'), ('健忘', '健忘'), ('厲害', '厲害'), ('正常', '正常'), ('懶惰', '懶惰')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='sth_adj',
            field=models.CharField(choices=[('扯', '扯'), ('蠢', '蠢'), ('煩', '煩'), ('北七', '北七'), ('北爛', '北爛'), ('誇張', '誇張'), ('有趣', '有趣'), ('好笑', '好笑'), ('丟臉', '丟臉'), ('瘋狂', '瘋狂'), ('誇張', '誇張'), ('無聊', '無聊'), ('幼稚', '幼稚'), ('難忘', '難忘'), ('開心', '開心')], max_length=100, null=True),
        ),
    ]
