# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20171216_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storys', to='story.StoryAuthor'),
        ),
    ]
