# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20171102_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='story',
            name='my_field2',
        ),
    ]
