# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20171111_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, to='story.Tag'),
        ),
    ]
