# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20171217_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAdjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='adjective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='story.PersonAdjective'),
        ),
    ]
