# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20171112_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_story', to='story.Tag'),
        ),
    ]
