# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20171217_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonAdjective',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='adjective_p',
            new_name='category',
        ),
    ]
